ISPN-13353 View configuration in json, xml and yaml
infinispan/infinispan-console pull request #184
Opened 2022-01-31 12:25 UTC by dipguptaredhat

2022-01-31 23:55 UTC, karesti commented
@dipguptaredhat I changed some code

2022-02-01 10:46 UTC, karesti requested changes
as discussed, create a custom hook and add unit test

2022-02-03 09:15 UTC, dipguptaredhat commented
@karesti Need your help on this error.

Got this when running jest test on CacheConfiguration.test.tsx

![Screenshot from 2022-02-02 16-30-48](https://user-images.githubusercontent.com/97534722/152142404-3a2a18cd-9236-466c-9119-a0a6e35f89ef.png)

2022-02-03 09:16 UTC, dipguptaredhat commented on src/__tests__/views/CacheConfiguration.test.tsx
> +    render(
@karesti Need your help on this error.

Got this when running jest test on CacheConfiguration.test.tsx

![Screenshot from 2022-02-02 16-30-48](https://user-images.githubusercontent.com/97534722/152142404-3a2a18cd-9236-466c-9119-a0a6e35f89ef.png)

2022-02-10 09:41 UTC, karesti approved these changes

2022-02-10 09:41 UTC, merged