ISPN-13690 Feature form for secured caches
infinispan/infinispan-console pull request #212
Opened 2022-05-10 05:26 UTC by dipguptaredhat

Feature secured cache added

2022-05-10 10:12 UTC, karesti requested changes
some changes that depend from the changes I added / asked in the indexing PR

2022-05-10 10:12 UTC, karesti commented on src/services/cacheService.ts
> +  public async getSecurityRoles(): Promise<Either<ActionResponse, string[]>> {
move to securityService
this method is unrelated to caches

2022-05-10 10:12 UTC, karesti commented on src/app/Caches/Create/Features/SecuredCache.tsx
> +        <Form>
check the Card and CardBody changes I reported in indexing to change this accordingly.

2022-05-10 10:12 UTC, karesti commented on src/app/Caches/Create/Features/SecuredCache.tsx
> +    // Options for Isolation Level
delete comment

2022-05-10 10:12 UTC, karesti commented on src/app/Caches/Create/Features/SecuredCache.tsx
> +    //Secured Cache
delete this comment, not necessary information

2022-05-12 05:40 UTC, dipguptaredhat commented
@karesti new commit added, in the last step create cache not working, please check

2022-05-17 11:10 UTC, karesti commented
@dipguptaredhat rebase needed from main! ping me DM when ready please!

2022-05-23 08:59 UTC, karesti commented
@dipguptaredhat choosing a role should be mandatory for secured caches next. otherwise we are at the end with a configuration that is not correct

```json
 "security": {
      "authorization": {
        "enabled": true,
        "roles": []
      }
    }
```

2022-05-23 09:04 UTC, karesti commented
@dipguptaredhat there was a bug in 13.0.10.Final and 14.x parsing the configuration of secured caches. works with 13.0.10.Final but it's not fixed in 14.0.0.Dev02
https://github.com/infinispan/infinispan/commit/82c1e00a2c7c6b8cc9e4950b9efde13eac5712a6

2022-05-23 10:18 UTC, oraNod commented
@karesti and @dipguptaredhat Hey, what do you think about changing this to "RBAC" instead of "secured"?

When I think of security I think of SSL/TLS so changing the label to RBAC might be more immediately descriptive to users. They'd know what to expect when they select the option.

I ask this because I can change the labels but they won't necessarily correspond to Infinispan types, etc. So I would propose that if we make this change we do a bit of refactoring to s/secured/rbac. I know that's a pain though. Sorry I didn't mention it earlier but I've been caught up in stuff.

2022-05-23 10:22 UTC, tristantarrant commented
I'm not sure the RBAC acronym is well-known enough. I'd think that ACL is much more common.

2022-05-23 10:28 UTC, oraNod commented
Maybe we could even go with "authorization" to be consistent with the schema?

2022-05-23 13:39 UTC, karesti commented
@oraNod make any doc/label change you need. I vote for authorization too

2022-05-23 13:40 UTC, karesti requested changes
Rename header label for Authorization instead of secured

Chose at least 1 role before moving forward.

2022-05-23 14:18 UTC, dipguptaredhat commented
@karesti changes done and squashed

2022-05-23 15:13 UTC, karesti approved these changes

2022-05-23 15:13 UTC, merged