ISPN-13894 Alert when protobuf schemas are updated
infinispan/infinispan-console pull request #232
Opened 2022-07-19 03:37 UTC by dipguptaredhat

https://issues.redhat.com/browse/ISPN-13894

Warning Alert is used, https://www.patternfly.org/v4/components/alert

2022-07-19 03:41 UTC, dipguptaredhat commented
Find one bug.

During editing a protobug, when we clear the content inside Schema and save it, it displays a spinner and further we can't edit to correct that. 

Need to have a validation before saving the edited schema? @karesti 

![Screenshot from 2022-07-19 09-07-27](https://user-images.githubusercontent.com/97534722/179659539-a91b539e-499e-481d-99d0-ec6e211da804.png)

2022-07-20 08:57 UTC, karesti requested changes

2022-07-20 08:57 UTC, karesti commented on src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
> +    if (loading) {
could we take the opportunity to refactor this part and use a hook ?

2022-07-26 06:17 UTC, dipguptaredhat commented
@karesti added a commit, to fetch schemas from hook.
The issue I am getting is when we add new schema the list is not getting updated.

2022-07-26 06:21 UTC, dipguptaredhat reviewed
@karesti added a commit, to fetch schemas from hook.
The issue I am getting is when we add new schema the list is not getting updated.

2022-07-26 06:21 UTC, dipguptaredhat commented on src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
> +    }
we need to setLoading(false) here, but how can we set that after if loop.

2022-07-27 10:21 UTC, karesti requested changes
Fix the error message (those can be seen in the dev tools in the console tab)

TextArea.js?6e2c:36 TextArea: TextArea requires either an id or aria-label to be specified

The hook should replace all the ConsoleServices calls, in every component.

2022-07-28 05:39 UTC, dipguptaredhat commented
> The hook should replace all the ConsoleServices calls, in every component.

When replacing this `protobufService.getSchema(schemaName).` with the hook, it's throwing an error `Error: Rendered more hooks than during the previous render.`

Maybe because this hook is called up multiple times, for all the schemas.

2022-07-28 05:40 UTC, dipguptaredhat reviewed
> The hook should replace all the ConsoleServices calls, in every component.

When replacing [this](https://github.com/infinispan/infinispan-console/blob/b192fe58edd3c2b5c21bf4fe43b16b1873ff2756/src/app/ProtoSchema/ProtobufSchemasDisplay.tsx#L92) `protobufService.getSchema(schemaName).` with the hook, it's throwing an error `Error: Rendered more hooks than during the previous render.`

Maybe because this hook is called up multiple times, for all the schemas.

2022-07-28 09:32 UTC, karesti requested changes
leave the hook use for all the calls out of this PR
however, the proto-schema.cy.js  is failing

2022-08-06 03:44 UTC, andyuk1986 approved these changes
Tests are passing now and I have checked all works fine. Thanks Dipanshu :)

2022-08-06 03:44 UTC, merged