ISPN-14057 Toolbar in Protobuf schema
infinispan/infinispan-console pull request #261
Opened 2022-09-27 08:14 UTC by pnaik1

This PR will resolve https://issues.redhat.com/browse/ISPN-14057

Please review my changes. :)

2022-09-27 08:18 UTC, dpanshug requested changes
Hi @pnaik1, Thanks for contributing

2022-09-27 08:18 UTC, dpanshug commented on src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
> +                    console.log(protoSchema.name);
Remove console statement

2022-09-27 08:20 UTC, dpanshug commented on src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
> +                    </DataListCell>,
Remove `,`

2022-09-27 10:55 UTC, dpanshug approved these changes

2022-09-27 11:12 UTC, dpanshug commented
The build is failing, need to check second commit [Merge branch 'infinispan:main' into changes](https://github.com/infinispan/infinispan-console/pull/261/commits/fd1403366a5754c8741db4550639d5debb3665c5)

2022-10-03 08:48 UTC, andyuk1986 commented
I am looking into failing test.

2022-10-03 10:05 UTC, andyuk1986 approved these changes
Tests fixed and passed.

2022-10-03 10:05 UTC, merged