ISPN-14092 Cache Configuration Wizard Direct Link
infinispan/infinispan-console pull request #264
Opened 2022-09-30 10:49 UTC by dpanshug

https://issues.redhat.com/browse/ISPN-14092

2022-10-03 09:45 UTC, karesti requested changes
squash commits please

2022-10-03 09:45 UTC, karesti commented on src/app/CacheManagers/CacheTableDisplay.tsx
> +    // Will remove comment when the feature is ready
remove comment

2022-10-03 09:45 UTC, karesti commented on src/app/Caches/Create/CreateCacheWizard.tsx
> +          if(ConsoleServices.security().hasConsoleACL(ConsoleACL.CREATE, connectedUser)){
active button is already init to true. check if the user has not the right and set it to false instead and break

2022-10-03 09:45 UTC, karesti commented on src/app/Caches/Create/CreateCacheWizard.tsx
> +          if(ConsoleServices.security().hasConsoleACL(ConsoleACL.CREATE, connectedUser)){
same code as above

2022-10-04 08:59 UTC, karesti commented
@dpanshug some comments to be addressed

2022-10-04 11:25 UTC, dpanshug commented
> @dpanshug some comments to be addressed

Done :+1:

2022-10-04 12:27 UTC, merged