ISPN-14130 Add the memory option in the data Distribution chart
infinispan/infinispan-console pull request #266
Opened 2022-10-10 11:46 UTC by dpanshug

https://issues.redhat.com/browse/ISPN-14130

2022-10-13 13:54 UTC, karesti requested changes
there is something with the formatter of the code that is not ok.
could you please run prettier? npm run format

2022-10-13 13:54 UTC, karesti commented on src/app/Caches/DataDistributionChart.tsx
> +      if (
code that does not change should not be changing format

2022-10-13 13:55 UTC, karesti requested changes

2022-10-13 13:55 UTC, karesti commented on src/app/Caches/DataDistributionChart.tsx
> +        return <Spinner size={'lg'} />;
the good practice is to englobe on ()

2022-10-13 13:55 UTC, karesti commented on src/app/Caches/DataDistributionChart.tsx
> +        return <TableErrorState error={error} />;
same here

2022-10-13 13:55 UTC, karesti commented on src/app/Caches/DataDistributionChart.tsx
> +      // Find max domain
is there any change in this code ?

2022-10-17 10:44 UTC, dpanshug commented
@karesti code might be changing because of prettier formatting, will create another PR for improving it in other files also.

2022-10-18 15:24 UTC, karesti requested changes

2022-10-20 07:53 UTC, karesti commented
@dpanshug needs rebase

2022-10-24 16:33 UTC, karesti commented
@dpanshug did you do any changes on this PR ?

2022-10-26 08:19 UTC, dpanshug commented
> @dpanshug did you do any changes on this PR ?

I've pushed the changes now.

2022-10-26 12:14 UTC, karesti requested changes
I'm testing the feature where the endpoint answers
``` json
[
  {
    "node_name": "3803a7d55fbe-10729",
    "node_addresses": [
      "172.17.0.2:7800"
    ],
    "memory_entries": 1,
    "total_entries": 1,
    "memory_used": 104
  }
]
```
And nothing is displayed. I added one entry to a cache with this config:

Cache config
```json
{
  "vvbvbvvbb": {
    "distributed-cache": {
      "owners": "1",
      "mode": "SYNC",
      "statistics": true,
      "encoding": {
        "key": {
          "media-type": "application/x-protostream"
        },
        "value": {
          "media-type": "application/x-protostream"
        }
      },
      "locking": {
        "isolation": "REPEATABLE_READ"
      },
      "memory": {
        "max-size": "56MB",
        "when-full": "REMOVE"
      }
    }
  }
}
```

2022-10-28 08:09 UTC, dpanshug commented
@karesti I've updated the validation for displaying memory_used, now `memory_used` will work only when `max-size` is configured.

2022-10-28 15:48 UTC, karesti requested changes
rebase please!

2022-11-02 12:29 UTC, karesti approved these changes

2022-11-02 12:29 UTC, merged