ISPN-14298 Delete a counter
infinispan/infinispan-console pull request #305
Opened 2023-01-03 09:36 UTC by dpanshug

https://issues.redhat.com/browse/ISPN-14298

2023-01-11 11:05 UTC, karesti requested changes
Several issues 

**Create Counter:**

* When we have radio buttons, one value needs to be selected by default
* Add popover tooltip like in the wizard form to explain What means storage Persistent/Volatile
*  Add popover tooltip to explain diff between strong and weak
* Initial value should be a number field, I can add anything
* We need a validation before trying to create the counter and do the alert

"Unexpected error creating counter dd "ISPN029508: Invalid initial value for counter. It must be between 22 and 22 (inclusive) but was 11" 
Before leaving the create form, we need those validations.

** Add Delta **
* I can add any delta even when I have upper bound and lower bound.
* The popup should contain the name of the counter since we don't know which counter we are changing once we open it, like remove.

** Reset **
The wording on the reset should contain more information about the counter. We don't know which is the  counter name or the values that will be reset, even if we do have that information.

There is something weird when we manipulate (add/remove). The page does not seem to get refreshed well. 
I need to dig more in the code details, I did more a behaviour review at this point.

2023-01-11 11:07 UTC, karesti commented on src/app/utils/counterUtils.ts
> +export function createCounterConfig(counterConfig) {
this can be unit tested

2023-01-16 17:28 UTC, dvagnero commented
Hi @dpanshug , I pushed one commit with docs suggestions. I'll take a look at the messages about invalid values tomorrow.
Two things I noticed.

- During counter creation I don't get a green check for the upper value 
![image](https://user-images.githubusercontent.com/58083949/212735925-41d1e1da-fe4c-44bf-879e-9ffdefe8054e.png)

- When I try to create a counter that has the same name as already existing counter I get a confirmation message but no counter is created.

2023-01-17 10:13 UTC, karesti commented
test failing now @dpanshug

2023-01-17 11:06 UTC, dvagnero commented
Added another commit @dpanshug

2023-01-18 05:34 UTC, dpanshug commented on src/app/assets/languages/en.json
> +      "modal-initial-value-invalid": "The initial value must be between the lower bound and the upper bound inclusively",
Only the upper bound is inclusive.

2023-01-18 05:38 UTC, dpanshug reviewed
@dvagnero Thanks for reviewing.

2023-01-18 05:40 UTC, dpanshug commented on src/app/assets/languages/en.json
> +      "modal-initial-value-invalid": "The initial value must be between the lower bound and the upper bound inclusively",
Only the upper bound is inclusive.

2023-01-18 11:47 UTC, dpanshug commented
> Hi @dpanshug , I pushed one commit with docs suggestions. I'll take a look at the messages about invalid values tomorrow. Two things I noticed.
> 
> * During counter creation I don't get a green check for the upper value
>   ![image](https://user-images.githubusercontent.com/58083949/212735925-41d1e1da-fe4c-44bf-879e-9ffdefe8054e.png)
> * When I try to create a counter that has the same name as already existing counter I get a confirmation message but no counter is created.

For the validation of upper bound, we already have validation for lower bound which states that it should be lesser than upper bound and similar for initial value also. 

![image](https://user-images.githubusercontent.com/97534722/213163067-28a79081-b01e-4015-b6ba-4891f598d8e4.png)

And for the same counter name issue, I have created a JIRA for improving the API [ISPN-14468](https://issues.redhat.com/browse/ISPN-14468)

2023-01-19 15:54 UTC, karesti approved these changes

2023-01-19 15:54 UTC, merged