Tasks
infinispan/infinispan-console pull request #313
Opened 2023-01-19 14:11 UTC by dpanshug

2023-02-13 14:51 UTC, karesti requested changes
I need the build working here

2023-03-06 16:16 UTC, karesti reviewed
The empty message is not ok

![Screenshot 2023-03-06 at 17 15 49](https://user-images.githubusercontent.com/233499/223168052-7a214541-f41e-4029-b7f9-a3d0ff5445ed.png)

2023-03-06 16:23 UTC, karesti commented
package.json lock should not be changed

2023-03-06 16:25 UTC, karesti commented
which script have you used to test the upload?
would be good for some testing @dpanshug

2023-03-07 10:13 UTC, karesti commented
@dpanshug needs rebase

2023-03-07 18:25 UTC, dvagnero commented
I need some hint what to put in the tooltip. https://infinispan.org/docs/stable/titles/server/server.html#remote-execution I see the tasks can be scripts or custom Java classes. Is it necessary to stop the server? etc.

2023-03-13 05:57 UTC, dpanshug commented
@dvagnero need to merge your commit with mine for a change

2023-03-14 04:24 UTC, dpanshug commented
> which script have you used to test the upload? would be good for some testing @dpanshug

Writing a E2E test for this.

2023-03-14 05:12 UTC, dpanshug commented
> I need some hint what to put in the tooltip. https://infinispan.org/docs/stable/titles/server/server.html#remote-execution I see the tasks can be scripts or custom Java classes. Is it necessary to stop the server? etc.

@tristantarrant can you help here pls.

2023-03-14 11:57 UTC, andyuk1986 commented
Cypress test looks good but scenario for task edit/save is not there.

2023-03-16 04:49 UTC, dpanshug commented
@dvagnero Found this in [documentation](https://infinispan.org/docs/stable/titles/server/server.html#remote-execution)
> You can implement tasks as custom Java classes or define scripts in languages such as JavaScript.` 

Maybe this info is useful for the tooltip.

2023-03-16 16:34 UTC, dvagnero commented
> @dvagnero Found this in [documentation](https://infinispan.org/docs/stable/titles/server/server.html#remote-execution)
> 
> > You can implement tasks as custom Java classes or define scripts in languages such as JavaScript.`
> 
> Maybe this info is useful for the tooltip.

Okay so it can be Java or Javascript. What about requirements? Having a script engine? Anything else?

2023-03-17 04:57 UTC, dpanshug commented
> Okay so it can be Java or Javascript. What about requirements? Having a script engine? Anything else?

For the JS task, you will need to install a JS script engine on the server, it won't work with JDK 17.

2023-03-17 16:40 UTC, dvagnero commented
Thank you for suggestions @dpanshug 
Is it necessary to stop the server before adding a task?

2023-03-20 12:42 UTC, andyuk1986 commented
@dvagnero just to add my two cents - as @tristantarrant said, there are 2 types of tasks: remote server tasks and Script Tasks. Console shows both Remote and Script Tasks. But at the moment (with this PR) it is possible to create/edit/execute only Script Tasks, and - no, for these tasks no Server restart is needed.
For Remote tasks the process is different -> jar file should be copied to server's data folder and server need to be restarted but I don't know if these use case will be covered with Console in the future.

2023-03-21 13:40 UTC, karesti requested changes
* When the task creation gives an error, the error should be displayed in the top of the popup and not in the alert. Otherwise we lose what we wrote in the editor.
First validate that the task was created, and if it's ok, close the popup and display an alert of ok.
* The task list should display the task that has been created

![image](https://user-images.githubusercontent.com/233499/226622954-e0cea06e-9c03-41c8-9ae4-2207be807770.png)

If the user can't see the task, we should not be displaying any alert but only listing the names of the tasks and disable the actions the user can't do. 

![image](https://user-images.githubusercontent.com/233499/226623493-13da72bf-48ce-456b-b149-45e1bc951145.png)

![image](https://user-images.githubusercontent.com/233499/226623811-8291ca61-c948-411d-bfe5-e0c86ba6620e.png)

2023-03-22 12:38 UTC, dvagnero commented
Thanks @andyuk1986 for the explanation. I was under the impression that we're aiming for both tasks and scripts.
 So @dpanshug and @karesti do you plan to add support for tasks written in Java? And if yes, would users use the same process to upload either a script or task?
Tasks and scripts have some similarities but also a different workflow and prerequisites (script engine, stopping server etc). What do you think about having a radio button to choose the Task type inside the Create a task dialogue? Or some other way to differentiate between these two?

2023-03-22 12:44 UTC, tristantarrant commented
There is no way to upload a Java task: it needs to be deployed before startup

2023-03-24 12:19 UTC, dpanshug commented
> The task list should display the task that has been created

@karesti I've tried fixing it, list gets updated when there already exist some tasks. But if you try to create the task for the first time, the API seems to not fetch the tasks list. Can you please help me out here. :)

2023-03-27 18:05 UTC, karesti commented
@dpanshug check how the entries add works plz

2023-04-11 14:11 UTC, dvagnero commented on src/app/Tasks/ExecuteTasks.tsx
> +          Do you want to execute <strong>{props.task?.name}</strong> ?
Hey @dpanshug , it looks good to me

2023-04-12 09:57 UTC, dpanshug commented
@karesti Pls check if this can be merged :)

2023-04-14 10:31 UTC, karesti commented
@dpanshug no, this feature can't be merged as it is. if the javascript engine is not available, we should disable the task creation. it is confusing and useless. for that we need an endpoint in the scripts that indicates that an js engine is available. 
I'm unable to test and understand he feature (as a user from the console).

2026-04-21 15:09 UTC, tristantarrant commented
Closing for now

2026-04-21 15:09 UTC, closed without merging