XSite Repl test environment is configured and new tests are added.
infinispan/infinispan-console pull request #360
Opened 2023-05-21 04:35 UTC by andyuk1986

2023-05-29 07:50 UTC, dpanshug commented
In addition, it would be beneficial to incorporate the `xsite.cy.js` test for thorough testing of this PR within the GitHub Actions workflow.

2023-05-29 07:51 UTC, dpanshug requested changes
In addition, it would be beneficial to incorporate the `xsite.cy.js` test for thorough testing of this PR within the GitHub Actions workflow.

2023-05-29 07:57 UTC, dpanshug commented on package.json
> +    "cy:run-xsite": "cypress run --headless --spec 'cypress/e2e/xsite.cy.js'"
The server `./run-xsite.tests.sh` stop after running, how can we then utilize this command?

2023-05-30 13:35 UTC, andyuk1986 commented
OK. I think I will change the whole test running scripts to work over docker and include also xsite tests in it. It will include run-server-for-e2e.sh as well as the pull request verification script.

2023-07-03 16:50 UTC, karesti commented
@andyuk1986 which is the status here ?

2023-07-03 20:14 UTC, andyuk1986 commented
@karesti I am updating the PR to include the xsite tests in PR checkups too, as well as to use the latest infinispan-dev-mode.xml in one general script.

2023-09-21 10:00 UTC, karesti commented
@andyuk1986 which is the status here 🙏🏻 ?

2023-09-21 13:29 UTC, andyuk1986 commented
Hey @karesti , at the moment this PR is on hold. I have some work in progress on my local, but there are other priorities now. As soon as I have some time, I will finish the work and will update this PR.

2024-10-16 09:02 UTC, karesti commented
@andyuk1986 we really need these tests to assure non regression on backups

2024-10-21 08:15 UTC, andyuk1986 commented
Hey Katia, I have started to work on it. Will be ready as soon as possible.

2024-10-21 09:21 UTC, karesti commented
@andyuk1986 thanks !!! :))

2024-11-01 11:02 UTC, andyuk1986 commented
@karesti I am closing this PR as it is really hard to resolve the conflicts after a year pause and changes from main. I have created new PR #540 which includes these changes on the clear rebased main.

2024-11-01 11:02 UTC, closed without merging