ISPN-14913 Create cache configuration
infinispan/infinispan-console pull request #369
Opened 2023-06-14 12:00 UTC by dpanshug

https://issues.redhat.com/browse/ISPN-14913

2023-06-15 08:12 UTC, dpanshug commented
This should be merged after #368

2023-07-04 08:11 UTC, karesti requested changes

2023-07-04 08:11 UTC, karesti commented on src/app/assets/languages/en.json
> +      "page-title-description": "You can only generate a new cache config and generate it. Note that the new cache will not be stored by Infinispan",
Infinispan is the brand variable to be replaced by Datagrid

2023-07-04 08:12 UTC, karesti commented
![Screenshot 2023-07-04 at 10 11 36](https://github.com/infinispan/infinispan-console/assets/233499/c96ca4be-d400-4b33-8b63-71458adf1d7e)

2023-07-04 08:14 UTC, karesti commented
@dpanshug is there any change related to the fact of creating "templates" instead of caches ?

2023-07-04 08:15 UTC, karesti commented
![Screenshot 2023-07-04 at 10 15 31](https://github.com/infinispan/infinispan-console/assets/233499/9ff8ef34-188b-4412-993f-1c2174417544)

misaligned

2023-07-04 08:16 UTC, karesti commented
the message above, you can add the Operator as well.

2023-07-05 11:44 UTC, dpanshug commented
> @dpanshug is there any change related to the fact of creating "templates" instead of caches ?

By change in creating "templates" do you mean creating cache config for users without create right? The only change is I've removed the cache setup from the sidebar.

2023-07-07 14:07 UTC, dpanshug commented
> @dpanshug is this preview ?

@andyuk1986 found some warnings during the test, waiting for a final check.

2023-07-12 04:10 UTC, andyuk1986 commented
Thank you @dpanshug, the issue with exceptions in the log is fixed.

2023-07-12 08:37 UTC, karesti commented on src/services/cacheService.ts
> +  public async convertToAllFormat(
@dpanshug  I added a method to wrap le 3 calls, and add a loading

2023-07-12 09:09 UTC, andyuk1986 commented
Tests started to fail, let me look into them.

2023-07-12 10:32 UTC, karesti commented
@andyuk1986 I changed the code so the formatting of the config does 3 calls and waits for them with a loading
do you have time to grab a look to the e2e part f it ?

2023-07-12 12:07 UTC, andyuk1986 commented
yes, looking into it.

2023-07-12 15:38 UTC, karesti commented
@andyuk1986 I accidentally pushed a wrong stuff! sorry wasting your time

2023-07-12 16:09 UTC, merged