ISPN-14914 Admin view for cache templates
infinispan/infinispan-console pull request #370
Opened 2023-06-19 09:44 UTC by dpanshug

https://issues.redhat.com/browse/ISPN-14914

2023-06-19 10:03 UTC, dpanshug commented
To be merged after #368

2023-06-29 18:57 UTC, andyuk1986 commented
I have rebased, and fixed the test. Looks good to me.

2023-06-30 07:04 UTC, dpanshug commented
Thanks @andyuk1986, I have fixed that problem.

2023-07-03 16:09 UTC, karesti requested changes
some console logs forgotten 
other wise

2023-07-03 16:09 UTC, karesti commented on src/app/services/cachesHook.ts
> +      console.log('d');
remove

2023-07-03 16:09 UTC, karesti commented on src/app/services/cachesHook.ts
> +            console.log('eitherConfigs', eitherConfigs);
remove

2023-07-03 16:09 UTC, karesti commented on src/app/services/cachesHook.ts
> +          setLoading(false);
if we do finally setLoading false no need to do it here, right ?

2023-07-04 08:03 UTC, karesti commented
@dpanshug related failing tests

2023-07-04 13:52 UTC, karesti approved these changes

2023-07-04 13:52 UTC, merged