ISPN-14962 Metrics tab
infinispan/infinispan-console pull request #375
Opened 2023-06-30 18:03 UTC by dpanshug

https://issues.redhat.com/browse/ISPN-14962

2023-07-03 16:15 UTC, karesti commented on src/services/cacheConfigUtils.ts
> +      } else {
else can be removed and chain, since there is the return

2023-07-03 16:15 UTC, karesti requested changes
small code change, but more about look and feel

2023-07-03 16:17 UTC, karesti commented
![Screenshot 2023-07-03 at 18 14 08](https://github.com/infinispan/infinispan-console/assets/233499/5bfb8ec6-e656-4003-a2ba-c87d294ef6cc)
The labels look very big for me. would not be better to use an smaller font ? 
Also I believe with approx. abbreviate labels are shorter too so we wont have the sized to be that weird

2023-07-03 16:19 UTC, karesti commented
![Screenshot 2023-07-03 at 18 18 28](https://github.com/infinispan/infinispan-console/assets/233499/e98b7d58-0c7e-481c-a216-efc4debf8804)
numbers are likely to be bigger that the labels on the right that have fixed size. Put more size for the number part

2023-07-06 07:06 UTC, dpanshug commented
The numbers are emphasized with a bolder font compared to the labels.
![image](https://github.com/infinispan/infinispan-console/assets/97534722/6626cb52-e662-4a03-9d0b-d61a7f4458e8)

Also, the labels are designed to be concise, with the shortest possible size of <p>. If we decrease the size further, we would need to use <small> which is lighter and less easily visible.
![image](https://github.com/infinispan/infinispan-console/assets/97534722/d7218a8f-4ea9-4be5-ba52-fe9e8c692ba5)

2023-07-06 14:09 UTC, karesti commented
@dpanshug there is a formatter for numbers

2023-07-10 07:07 UTC, dpanshug commented
@karesti how this looks?

![Screenshot from 2023-07-10 12-33-00](https://github.com/infinispan/infinispan-console/assets/97534722/bfcd4c9c-9908-4c09-9c1d-866524a0f868)

2023-07-11 07:23 UTC, karesti commented
@dpanshug looks well but still a couple of things:

1) the approximate is too big. Could be use the abbreviation for this? I think Approx. is enough.
2) the Data access part, I would like to see a screenshot with very big numbers, because this will be the case. Those numbers must be formatted using the format utility.

2023-07-11 07:58 UTC, dpanshug commented
@karesti 

Numbers are formatted using `displayUtils.formatNumber()`

![image](https://github.com/infinispan/infinispan-console/assets/97534722/8a84f2db-9084-458d-83a6-14bab6934810)

2023-07-11 10:15 UTC, karesti approved these changes

2023-07-11 10:15 UTC, merged